version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: travelbuddy-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: travelbuddy-backend
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb://mongo:27017/travelbuddy
      - JWT_SECRET=change-me
      - FRONTEND_URL=http://localhost:5173
      - CORS_ORIGIN=http://localhost:5173
      # - GOOGLE_CLIENT_ID=
      # - GOOGLE_CLIENT_SECRET=
    ports:
      - "5001:5001"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=http://localhost:5001/api
        - VITE_SOCKET_URL=http://localhost:5001
    container_name: travelbuddy-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo-data:

